webtalk_init -webtalk_dir C:/Users/Agasha/Documents/University/FunctionalCircuitDesign/lab4/code/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/bist_normal_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec 24 17:08:10 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8e79fdbe-d9b3-496f-be29-1067da3c42ca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6235fa0e405541aeb0dc0d8997c6bd65" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2495 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "5.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7932065 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.28_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14792_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1418175277 -regid "" -xml C:/Users/Agasha/Documents/University/FunctionalCircuitDesign/lab4/code/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/bist_normal_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Agasha/Documents/University/FunctionalCircuitDesign/lab4/code/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/bist_normal_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Agasha/Documents/University/FunctionalCircuitDesign/lab4/code/lab4/lab4.sim/sim_1/behav/xsim/xsim.dir/bist_normal_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
